/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as BillboardRouteImport } from './routes/billboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesSlugRouteImport } from './routes/series.$slug'
import { Route as ReadTranslationIdRouteImport } from './routes/read.$translationId'
import { Route as JobJobIdRouteImport } from './routes/job.$jobId'
import { Route as AdminGlossaryRouteImport } from './routes/admin.glossary'
import { Route as TranslateSlugChapterLangRouteImport } from './routes/translate.$slug.$chapter.$lang'
import { Route as SeriesSlugChapterChapterRouteImport } from './routes/series.$slug.chapter.$chapter'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const BillboardRoute = BillboardRouteImport.update({
  id: '/billboard',
  path: '/billboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSlugRoute = SeriesSlugRouteImport.update({
  id: '/series/$slug',
  path: '/series/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadTranslationIdRoute = ReadTranslationIdRouteImport.update({
  id: '/read/$translationId',
  path: '/read/$translationId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobJobIdRoute = JobJobIdRouteImport.update({
  id: '/job/$jobId',
  path: '/job/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGlossaryRoute = AdminGlossaryRouteImport.update({
  id: '/admin/glossary',
  path: '/admin/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateSlugChapterLangRoute =
  TranslateSlugChapterLangRouteImport.update({
    id: '/translate/$slug/$chapter/$lang',
    path: '/translate/$slug/$chapter/$lang',
    getParentRoute: () => rootRouteImport,
  } as any)
const SeriesSlugChapterChapterRoute =
  SeriesSlugChapterChapterRouteImport.update({
    id: '/chapter/$chapter',
    path: '/chapter/$chapter',
    getParentRoute: () => SeriesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billboard': typeof BillboardRoute
  '/catalogue': typeof CatalogueRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/glossary': typeof AdminGlossaryRoute
  '/job/$jobId': typeof JobJobIdRoute
  '/read/$translationId': typeof ReadTranslationIdRoute
  '/series/$slug': typeof SeriesSlugRouteWithChildren
  '/series/$slug/chapter/$chapter': typeof SeriesSlugChapterChapterRoute
  '/translate/$slug/$chapter/$lang': typeof TranslateSlugChapterLangRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billboard': typeof BillboardRoute
  '/catalogue': typeof CatalogueRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/glossary': typeof AdminGlossaryRoute
  '/job/$jobId': typeof JobJobIdRoute
  '/read/$translationId': typeof ReadTranslationIdRoute
  '/series/$slug': typeof SeriesSlugRouteWithChildren
  '/series/$slug/chapter/$chapter': typeof SeriesSlugChapterChapterRoute
  '/translate/$slug/$chapter/$lang': typeof TranslateSlugChapterLangRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billboard': typeof BillboardRoute
  '/catalogue': typeof CatalogueRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/glossary': typeof AdminGlossaryRoute
  '/job/$jobId': typeof JobJobIdRoute
  '/read/$translationId': typeof ReadTranslationIdRoute
  '/series/$slug': typeof SeriesSlugRouteWithChildren
  '/series/$slug/chapter/$chapter': typeof SeriesSlugChapterChapterRoute
  '/translate/$slug/$chapter/$lang': typeof TranslateSlugChapterLangRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billboard'
    | '/catalogue'
    | '/pricing'
    | '/profile'
    | '/reset-password'
    | '/robots.txt'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/admin/glossary'
    | '/job/$jobId'
    | '/read/$translationId'
    | '/series/$slug'
    | '/series/$slug/chapter/$chapter'
    | '/translate/$slug/$chapter/$lang'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billboard'
    | '/catalogue'
    | '/pricing'
    | '/profile'
    | '/reset-password'
    | '/robots.txt'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/admin/glossary'
    | '/job/$jobId'
    | '/read/$translationId'
    | '/series/$slug'
    | '/series/$slug/chapter/$chapter'
    | '/translate/$slug/$chapter/$lang'
  id:
    | '__root__'
    | '/'
    | '/billboard'
    | '/catalogue'
    | '/pricing'
    | '/profile'
    | '/reset-password'
    | '/robots.txt'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/admin/glossary'
    | '/job/$jobId'
    | '/read/$translationId'
    | '/series/$slug'
    | '/series/$slug/chapter/$chapter'
    | '/translate/$slug/$chapter/$lang'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillboardRoute: typeof BillboardRoute
  CatalogueRoute: typeof CatalogueRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminGlossaryRoute: typeof AdminGlossaryRoute
  JobJobIdRoute: typeof JobJobIdRoute
  ReadTranslationIdRoute: typeof ReadTranslationIdRoute
  SeriesSlugRoute: typeof SeriesSlugRouteWithChildren
  TranslateSlugChapterLangRoute: typeof TranslateSlugChapterLangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billboard': {
      id: '/billboard'
      path: '/billboard'
      fullPath: '/billboard'
      preLoaderRoute: typeof BillboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$slug': {
      id: '/series/$slug'
      path: '/series/$slug'
      fullPath: '/series/$slug'
      preLoaderRoute: typeof SeriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$translationId': {
      id: '/read/$translationId'
      path: '/read/$translationId'
      fullPath: '/read/$translationId'
      preLoaderRoute: typeof ReadTranslationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job/$jobId': {
      id: '/job/$jobId'
      path: '/job/$jobId'
      fullPath: '/job/$jobId'
      preLoaderRoute: typeof JobJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/glossary': {
      id: '/admin/glossary'
      path: '/admin/glossary'
      fullPath: '/admin/glossary'
      preLoaderRoute: typeof AdminGlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate/$slug/$chapter/$lang': {
      id: '/translate/$slug/$chapter/$lang'
      path: '/translate/$slug/$chapter/$lang'
      fullPath: '/translate/$slug/$chapter/$lang'
      preLoaderRoute: typeof TranslateSlugChapterLangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$slug/chapter/$chapter': {
      id: '/series/$slug/chapter/$chapter'
      path: '/chapter/$chapter'
      fullPath: '/series/$slug/chapter/$chapter'
      preLoaderRoute: typeof SeriesSlugChapterChapterRouteImport
      parentRoute: typeof SeriesSlugRoute
    }
  }
}

interface SeriesSlugRouteChildren {
  SeriesSlugChapterChapterRoute: typeof SeriesSlugChapterChapterRoute
}

const SeriesSlugRouteChildren: SeriesSlugRouteChildren = {
  SeriesSlugChapterChapterRoute: SeriesSlugChapterChapterRoute,
}

const SeriesSlugRouteWithChildren = SeriesSlugRoute._addFileChildren(
  SeriesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillboardRoute: BillboardRoute,
  CatalogueRoute: CatalogueRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminGlossaryRoute: AdminGlossaryRoute,
  JobJobIdRoute: JobJobIdRoute,
  ReadTranslationIdRoute: ReadTranslationIdRoute,
  SeriesSlugRoute: SeriesSlugRouteWithChildren,
  TranslateSlugChapterLangRoute: TranslateSlugChapterLangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
